### ISSUE TITLE
keine Geräte oder Entitäten ! nicht geladen

### ISSUE THREAD

**Issue by holger1982** [dupondje/nrgkick-ha#25]
Hi!

I copied all folders into custom_components/nrgkick/
Then I installed the integration and insert the url. So far so good, but there are no entities.
What did I wrong, or is there something missing?

**Comment by dupondje** [comment]
What does the logs show?

**Comment by holger1982** [comment]
Ok, iam relatively new to HA. Where can I watch the logs and what do you mean with use HACS? HACS is installed and running. Where do I have to put the hacs.json folder?

Thank you for your support!

**Comment by holger1982** [comment]
Is it possible to install the integration via HACS? I cant`t find an repository link..

**Comment by tgfuellner** [comment]
Hi, I have the same Problem:
I can't use HACS. HA is running in a container. I know, its not good
My log says:

Logger: homeassistant.config_entries
Quelle: config_entries.py:586
Erstmals aufgetreten: 09:54:00 (4 Vorkommnisse)
Zuletzt protokolliert: 09:57:48

Error setting up entry Nrgkick for nrgkick
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 586, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nrgkick/__init__.py", line 88, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2046, in async_forward_entry_setups
    await integration.async_get_platforms(platforms)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1177, in async_get_platforms
    import_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1177, in async_get_platforms
    import_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1177, in async_get_platforms
    import_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1165, in async_get_platforms
    platforms.update(self._load_platforms(platform_names))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1090, in _load_platforms
    platform_name: self._load_platform(platform_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1264, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1296, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/nrgkick/sensor.py", line 14, in <module>
    from homeassistant.const import (
ImportError: cannot import name 'UnitOfReactivePower' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)

**Comment by dupondje** [comment]
That seems like an outdated HA installation

**Comment by tgfuellner** [comment]
Bingo, is working after an upgrade
